project_name_override: spacetraders_api_client
package_name_override: spacetraders_api_client
post_hooks:
  - "isort ."
  - "black ."
  - "ruff . --fix"
use_path_prefixes_for_title_model_names: false
